Remove ssl checks possibly causing an error
I hope that this works, otherwise I'm reimplementing basename or just hardcoding it (an appealing option at this point)

Error being fixed:
[WARNING]: Skipping plugin (/usr/lib/python3/dist-packages/ansible/plugins/filter/core.py) as it seems to be invalid: cannot import
name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.9/dist-packages/jinja2/filters.py)
[WARNING]: Skipping plugin (/usr/lib/python3/dist-packages/ansible/plugins/filter/mathstuff.py) as it seems to be invalid: cannot
import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.9/dist-packages/jinja2/filters.py)
[WARNING]: an unexpected error occurred during Jinja2 environment setup: cannot import name 'environmentfilter' from 'jinja2.filters'
(/usr/local/lib/python3.9/dist-packages/jinja2/filters.py)   line 0
fatal: [elasticmaster]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: cannot import name 'environmentfilter' from 'jinja2.filters' (/usr/local/lib/python3.9/dist-packages/jinja2/filters.py)\n  line 0. String: \n{% if es_config %}\n{{ es_config | to_nice_yaml(indent=2) }}\n{% endif %}\n\n{% if es_config['cluster.name'] is not defined %}\ncluster.name: elasticsearch\n{% endif %}\n\n{% if es_config['node.name'] is not defined %}\nnode.name: {{inventory_hostname}}\n{% endif %}\n\n#################################### Paths ####################################\n\n# Path to directory containing configuration (this file and logging.yml):\n\npath.data: {{ es_data_dirs | array_to_str }}\n\npath.logs: {{ es_log_dir }}\n\n{% if es_path_repo is defined %}\npath.repo: {{ es_path_repo }}\n{% endif %}\n\n{% if es_action_auto_create_index == true %}\naction.auto_create_index: true\n{% elif not es_action_auto_create_index %}\naction.auto_create_index: false\n{% else %}\naction.auto_create_index: {{ es_action_auto_create_index }}\n{% endif %}\n\n{% if not oss_version and es_api_basic_auth_username is defined and es_api_basic_auth_password is defined %}\nxpack.security.enabled: true\n\n{% if es_enable_transport_ssl and es_enable_auto_ssl_configuration %}\nxpack.security.transport.ssl.enabled: true\nxpack.security.transport.ssl.verification_mode: \"{{ es_ssl_verification_mode }}\"\n{% if es_ssl_keystore and es_ssl_truststore %}\nxpack.security.transport.ssl.keystore.path: \"{{ es_ssl_certificate_path }}/{{ es_ssl_keystore | basename }}\"\nxpack.security.transport.ssl.truststore.path: \"{{ es_ssl_certificate_path }}/{{ es_ssl_truststore | basename }}\"\n{% elif es_ssl_key and  es_ssl_certificate %}\nxpack.security.transport.ssl.key: \"{{ es_ssl_certificate_path }}/{{ es_ssl_key | basename }}\"\nxpack.security.transport.ssl.certificate: \"{{ es_ssl_certificate_path }}/{{ es_ssl_certificate | basename }}\"\n{% if es_ssl_certificate_authority %}\nxpack.security.transport.ssl.certificate_authorities: \"{{ es_ssl_certificate_path }}/{{ es_ssl_certificate_authority | basename }}\"\n{% endif %}\n{% endif %}\n{% endif %}\n\n{% if es_enable_http_ssl and es_enable_auto_ssl_configuration %}\nxpack.security.http.ssl.enabled: true\n{% if es_ssl_keystore and es_ssl_truststore %}\nxpack.security.http.ssl.keystore.path: \"{{ es_ssl_certificate_path }}/{{ es_ssl_keystore | basename }}\"\nxpack.security.http.ssl.truststore.path: \"{{ es_ssl_certificate_path }}/{{ es_ssl_truststore | basename }}\"\n{% elif es_ssl_key and  es_ssl_certificate %}\nxpack.security.http.ssl.key: \"{{ es_ssl_certificate_path }}/{{ es_ssl_key | basename }}\"\nxpack.security.http.ssl.certificate: \"{{ es_ssl_certificate_path }}/{{ es_ssl_certificate | basename }}\"\n{% if es_ssl_certificate_authority %}\nxpack.security.http.ssl.certificate_authorities: \"{{ es_ssl_certificate_path }}/{{ es_ssl_certificate_authority | basename }}\"\n{% endif %}\n{% endif %}\n{% endif %}\n{% endif %}\n\n{% if es_mail_config is defined %}\nxpack.notification.email:\n  account:\n    {{ es_mail_config['account'] }}:\n      profile: {{ es_mail_config['profile'] }}\n      email_defaults:\n        from: {{ es_mail_config['from'] }}\n      smtp:\n        auth: {{ es_mail_config['require_auth'] }}\n        host: {{ es_mail_config['host'] }}\n        port: {{ es_mail_config['port'] }}\n        {% if es_mail_config['require_auth'] == true -%}\n        user: {{ es_mail_config['user'] }}\n        password: {{ es_mail_config['pass'] }}\n        {%- endif %}\n{% endif %}\n"}